spring:
  # Database Configuration (Production)
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: diFcUjHloMRrPoCGoCbkDpeevwIVtJjQ
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration (Production)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  # Redis Configuration (Production)
  data:
    redis:
      url: redis://default:GOwUPRpFGRVtZMSiEEWlTapCvefmpsFj@hopper.proxy.rlwy.net:11415

  # Kafka Configuration (Production)
  kafka:
    bootstrap-servers: shortline.proxy.rlwy.net:57987
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: appointment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"

# Logging (Production)
logging:
  level:
    root: WARN
    com.medibridge: INFO
    org.springframework.data.redis: WARN
